/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BecomeATutorRouteImport } from './routes/become-a-tutor'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as JoinRouteImport } from './routes/join'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedSavedPostsRouteImport } from './routes/_authenticated.saved-posts'
import { Route as TutorsIndexRouteImport } from './routes/tutors.index'
import { Route as TutorsTutorCodeRouteImport } from './routes/tutors.$tutorCode'
import { Route as AuthenticatedAdminCasesRouteImport } from './routes/_authenticated.admin.cases'
import { Route as AuthenticatedAdminR2RouteImport } from './routes/_authenticated.admin.r2'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated.admin.settings'
import { Route as AuthenticatedAdminTutorsRouteImport } from './routes/_authenticated.admin.tutors'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated.admin.users'
import { Route as AuthenticatedCasesIndexRouteImport } from './routes/_authenticated.cases.index'
import { Route as AuthenticatedCasesCaseIdRouteImport } from './routes/_authenticated.cases.$caseId'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeATutorRoute = BecomeATutorRouteImport.update({
  id: '/become-a-tutor',
  path: '/become-a-tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSavedPostsRoute = AuthenticatedSavedPostsRouteImport.update({
  id: '/saved-posts',
  path: '/saved-posts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const TutorsIndexRoute = TutorsIndexRouteImport.update({
  id: '/tutors/',
  path: '/tutors/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorsTutorCodeRoute = TutorsTutorCodeRouteImport.update({
  id: '/tutors/$tutorCode',
  path: '/tutors/$tutorCode',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminCasesRoute = AuthenticatedAdminCasesRouteImport.update({
  id: '/admin/cases',
  path: '/admin/cases',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminR2Route = AuthenticatedAdminR2RouteImport.update({
  id: '/admin/r2',
  path: '/admin/r2',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminTutorsRoute =
  AuthenticatedAdminTutorsRouteImport.update({
    id: '/admin/tutors',
    path: '/admin/tutors',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCasesIndexRoute = AuthenticatedCasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCasesCaseIdRoute =
  AuthenticatedCasesCaseIdRouteImport.update({
    id: '/cases/$caseId',
    path: '/cases/$caseId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/become-a-tutor': typeof BecomeATutorRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/join': typeof JoinRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/saved-posts': typeof AuthenticatedSavedPostsRoute
  '/tutors/$tutorCode': typeof TutorsTutorCodeRoute
  '/tutors/': typeof TutorsIndexRoute
  '/admin/cases': typeof AuthenticatedAdminCasesRoute
  '/admin/r2': typeof AuthenticatedAdminR2Route
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/tutors': typeof AuthenticatedAdminTutorsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/cases/$caseId': typeof AuthenticatedCasesCaseIdRoute
  '/cases/': typeof AuthenticatedCasesIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/become-a-tutor': typeof BecomeATutorRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/join': typeof JoinRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/saved-posts': typeof AuthenticatedSavedPostsRoute
  '/tutors/$tutorCode': typeof TutorsTutorCodeRoute
  '/tutors': typeof TutorsIndexRoute
  '/admin/cases': typeof AuthenticatedAdminCasesRoute
  '/admin/r2': typeof AuthenticatedAdminR2Route
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/tutors': typeof AuthenticatedAdminTutorsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/cases/$caseId': typeof AuthenticatedCasesCaseIdRoute
  '/cases': typeof AuthenticatedCasesIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/become-a-tutor': typeof BecomeATutorRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/join': typeof JoinRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/saved-posts': typeof AuthenticatedSavedPostsRoute
  '/tutors/$tutorCode': typeof TutorsTutorCodeRoute
  '/tutors/': typeof TutorsIndexRoute
  '/_authenticated/admin/cases': typeof AuthenticatedAdminCasesRoute
  '/_authenticated/admin/r2': typeof AuthenticatedAdminR2Route
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/tutors': typeof AuthenticatedAdminTutorsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/cases/$caseId': typeof AuthenticatedCasesCaseIdRoute
  '/_authenticated/cases/': typeof AuthenticatedCasesIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/become-a-tutor'
    | '/faq'
    | '/how-it-works'
    | '/join'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/dashboard'
    | '/saved-posts'
    | '/tutors/$tutorCode'
    | '/tutors/'
    | '/admin/cases'
    | '/admin/r2'
    | '/admin/settings'
    | '/admin/tutors'
    | '/admin/users'
    | '/cases/$caseId'
    | '/cases/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/become-a-tutor'
    | '/faq'
    | '/how-it-works'
    | '/join'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/dashboard'
    | '/saved-posts'
    | '/tutors/$tutorCode'
    | '/tutors'
    | '/admin/cases'
    | '/admin/r2'
    | '/admin/settings'
    | '/admin/tutors'
    | '/admin/users'
    | '/cases/$caseId'
    | '/cases'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/become-a-tutor'
    | '/faq'
    | '/how-it-works'
    | '/join'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/_authenticated/saved-posts'
    | '/tutors/$tutorCode'
    | '/tutors/'
    | '/_authenticated/admin/cases'
    | '/_authenticated/admin/r2'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/tutors'
    | '/_authenticated/admin/users'
    | '/_authenticated/cases/$caseId'
    | '/_authenticated/cases/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  BecomeATutorRoute: typeof BecomeATutorRoute
  FaqRoute: typeof FaqRoute
  HowItWorksRoute: typeof HowItWorksRoute
  JoinRoute: typeof JoinRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TutorsTutorCodeRoute: typeof TutorsTutorCodeRoute
  TutorsIndexRoute: typeof TutorsIndexRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-tutor': {
      id: '/become-a-tutor'
      path: '/become-a-tutor'
      fullPath: '/become-a-tutor'
      preLoaderRoute: typeof BecomeATutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/saved-posts': {
      id: '/_authenticated/saved-posts'
      path: '/saved-posts'
      fullPath: '/saved-posts'
      preLoaderRoute: typeof AuthenticatedSavedPostsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/tutors/': {
      id: '/tutors/'
      path: '/tutors'
      fullPath: '/tutors/'
      preLoaderRoute: typeof TutorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutors/$tutorCode': {
      id: '/tutors/$tutorCode'
      path: '/tutors/$tutorCode'
      fullPath: '/tutors/$tutorCode'
      preLoaderRoute: typeof TutorsTutorCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/cases': {
      id: '/_authenticated/admin/cases'
      path: '/admin/cases'
      fullPath: '/admin/cases'
      preLoaderRoute: typeof AuthenticatedAdminCasesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/r2': {
      id: '/_authenticated/admin/r2'
      path: '/admin/r2'
      fullPath: '/admin/r2'
      preLoaderRoute: typeof AuthenticatedAdminR2RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/tutors': {
      id: '/_authenticated/admin/tutors'
      path: '/admin/tutors'
      fullPath: '/admin/tutors'
      preLoaderRoute: typeof AuthenticatedAdminTutorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cases/': {
      id: '/_authenticated/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof AuthenticatedCasesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cases/$caseId': {
      id: '/_authenticated/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof AuthenticatedCasesCaseIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSavedPostsRoute: typeof AuthenticatedSavedPostsRoute
  AuthenticatedAdminCasesRoute: typeof AuthenticatedAdminCasesRoute
  AuthenticatedAdminR2Route: typeof AuthenticatedAdminR2Route
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTutorsRoute: typeof AuthenticatedAdminTutorsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedCasesCaseIdRoute: typeof AuthenticatedCasesCaseIdRoute
  AuthenticatedCasesIndexRoute: typeof AuthenticatedCasesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSavedPostsRoute: AuthenticatedSavedPostsRoute,
  AuthenticatedAdminCasesRoute: AuthenticatedAdminCasesRoute,
  AuthenticatedAdminR2Route: AuthenticatedAdminR2Route,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminTutorsRoute: AuthenticatedAdminTutorsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedCasesCaseIdRoute: AuthenticatedCasesCaseIdRoute,
  AuthenticatedCasesIndexRoute: AuthenticatedCasesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  BecomeATutorRoute: BecomeATutorRoute,
  FaqRoute: FaqRoute,
  HowItWorksRoute: HowItWorksRoute,
  JoinRoute: JoinRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TutorsTutorCodeRoute: TutorsTutorCodeRoute,
  TutorsIndexRoute: TutorsIndexRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
