/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BecomeATutorRouteImport } from './routes/become-a-tutor'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TutorsIndexRouteImport } from './routes/tutors.index'
import { Route as TutorsTutorCodeRouteImport } from './routes/tutors.$tutorCode'
import { Route as AuthenticatedPostCaseRouteImport } from './routes/_authenticated.post-case'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedCasesIndexRouteImport } from './routes/_authenticated.cases.index'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated.admin.users'
import { Route as AuthenticatedAdminTutorsRouteImport } from './routes/_authenticated.admin.tutors'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated.admin.settings'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as AuthenticatedPostCaseSuccessCaseIdRouteImport } from './routes/_authenticated.post-case.success.$caseId'

const BecomeATutorRoute = BecomeATutorRouteImport.update({
  id: '/become-a-tutor',
  path: '/become-a-tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorsIndexRoute = TutorsIndexRouteImport.update({
  id: '/tutors/',
  path: '/tutors/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorsTutorCodeRoute = TutorsTutorCodeRouteImport.update({
  id: '/tutors/$tutorCode',
  path: '/tutors/$tutorCode',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPostCaseRoute = AuthenticatedPostCaseRouteImport.update({
  id: '/post-case',
  path: '/post-case',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCasesIndexRoute = AuthenticatedCasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminTutorsRoute =
  AuthenticatedAdminTutorsRouteImport.update({
    id: '/admin/tutors',
    path: '/admin/tutors',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPostCaseSuccessCaseIdRoute =
  AuthenticatedPostCaseSuccessCaseIdRouteImport.update({
    id: '/success/$caseId',
    path: '/success/$caseId',
    getParentRoute: () => AuthenticatedPostCaseRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/become-a-tutor': typeof BecomeATutorRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/post-case': typeof AuthenticatedPostCaseRouteWithChildren
  '/tutors/$tutorCode': typeof TutorsTutorCodeRoute
  '/tutors/': typeof TutorsIndexRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/tutors': typeof AuthenticatedAdminTutorsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/cases/': typeof AuthenticatedCasesIndexRoute
  '/post-case/success/$caseId': typeof AuthenticatedPostCaseSuccessCaseIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/become-a-tutor': typeof BecomeATutorRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/post-case': typeof AuthenticatedPostCaseRouteWithChildren
  '/tutors/$tutorCode': typeof TutorsTutorCodeRoute
  '/tutors': typeof TutorsIndexRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/tutors': typeof AuthenticatedAdminTutorsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/cases': typeof AuthenticatedCasesIndexRoute
  '/post-case/success/$caseId': typeof AuthenticatedPostCaseSuccessCaseIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/become-a-tutor': typeof BecomeATutorRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/post-case': typeof AuthenticatedPostCaseRouteWithChildren
  '/tutors/$tutorCode': typeof TutorsTutorCodeRoute
  '/tutors/': typeof TutorsIndexRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/tutors': typeof AuthenticatedAdminTutorsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/cases/': typeof AuthenticatedCasesIndexRoute
  '/_authenticated/post-case/success/$caseId': typeof AuthenticatedPostCaseSuccessCaseIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/become-a-tutor'
    | '/dashboard'
    | '/post-case'
    | '/tutors/$tutorCode'
    | '/tutors/'
    | '/admin/settings'
    | '/admin/tutors'
    | '/admin/users'
    | '/cases/'
    | '/post-case/success/$caseId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/become-a-tutor'
    | '/dashboard'
    | '/post-case'
    | '/tutors/$tutorCode'
    | '/tutors'
    | '/admin/settings'
    | '/admin/tutors'
    | '/admin/users'
    | '/cases'
    | '/post-case/success/$caseId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/become-a-tutor'
    | '/_authenticated/dashboard'
    | '/_authenticated/post-case'
    | '/tutors/$tutorCode'
    | '/tutors/'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/tutors'
    | '/_authenticated/admin/users'
    | '/_authenticated/cases/'
    | '/_authenticated/post-case/success/$caseId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  BecomeATutorRoute: typeof BecomeATutorRoute
  TutorsTutorCodeRoute: typeof TutorsTutorCodeRoute
  TutorsIndexRoute: typeof TutorsIndexRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/become-a-tutor': {
      id: '/become-a-tutor'
      path: '/become-a-tutor'
      fullPath: '/become-a-tutor'
      preLoaderRoute: typeof BecomeATutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutors/': {
      id: '/tutors/'
      path: '/tutors'
      fullPath: '/tutors/'
      preLoaderRoute: typeof TutorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutors/$tutorCode': {
      id: '/tutors/$tutorCode'
      path: '/tutors/$tutorCode'
      fullPath: '/tutors/$tutorCode'
      preLoaderRoute: typeof TutorsTutorCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/post-case': {
      id: '/_authenticated/post-case'
      path: '/post-case'
      fullPath: '/post-case'
      preLoaderRoute: typeof AuthenticatedPostCaseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cases/': {
      id: '/_authenticated/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof AuthenticatedCasesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/tutors': {
      id: '/_authenticated/admin/tutors'
      path: '/admin/tutors'
      fullPath: '/admin/tutors'
      preLoaderRoute: typeof AuthenticatedAdminTutorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/post-case/success/$caseId': {
      id: '/_authenticated/post-case/success/$caseId'
      path: '/success/$caseId'
      fullPath: '/post-case/success/$caseId'
      preLoaderRoute: typeof AuthenticatedPostCaseSuccessCaseIdRouteImport
      parentRoute: typeof AuthenticatedPostCaseRoute
    }
  }
}

interface AuthenticatedPostCaseRouteChildren {
  AuthenticatedPostCaseSuccessCaseIdRoute: typeof AuthenticatedPostCaseSuccessCaseIdRoute
}

const AuthenticatedPostCaseRouteChildren: AuthenticatedPostCaseRouteChildren = {
  AuthenticatedPostCaseSuccessCaseIdRoute:
    AuthenticatedPostCaseSuccessCaseIdRoute,
}

const AuthenticatedPostCaseRouteWithChildren =
  AuthenticatedPostCaseRoute._addFileChildren(
    AuthenticatedPostCaseRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPostCaseRoute: typeof AuthenticatedPostCaseRouteWithChildren
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTutorsRoute: typeof AuthenticatedAdminTutorsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedCasesIndexRoute: typeof AuthenticatedCasesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPostCaseRoute: AuthenticatedPostCaseRouteWithChildren,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminTutorsRoute: AuthenticatedAdminTutorsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedCasesIndexRoute: AuthenticatedCasesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  BecomeATutorRoute: BecomeATutorRoute,
  TutorsTutorCodeRoute: TutorsTutorCodeRoute,
  TutorsIndexRoute: TutorsIndexRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
